name: Build and Release SEN Tool

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish for win-x64
        run: dotnet publish Shell/Sen.csproj -c Release -r win-x64 --self-contained true -o publish/win-x64

      - name: Publish for win-x86
        run: dotnet publish Shell/Sen.csproj -c Release -r win-x86 --self-contained true -o publish/win-x86

      - name: Publish for win-arm64
        run: dotnet publish Shell/Sen.csproj -c Release -r win-arm64 --self-contained true -o publish/win-arm64

      - name: Zip outputs
        run: |
          Compress-Archive -Path "publish/win-x64/*" -DestinationPath "sen.win-x64.zip"
          Compress-Archive -Path "publish/win-x86/*" -DestinationPath "sen.win-x86.zip"
          Compress-Archive -Path "publish/win-arm64/*" -DestinationPath "sen.win-arm64.zip"
        shell: pwsh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sen.win-x64.zip
            sen.win-x86.zip
            sen.win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
