name: Build Shell Tool

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true
          dotnet publish -c Release -r win-x86 --self-contained true
          dotnet publish -c Release -r win-arm64 --self-contained true

      - name: Zip outputs
        run: |
          Compress-Archive -Path "bin/Release/net8.0/win-x64/publish/*" -DestinationPath "shell.win-x64.zip"
          Compress-Archive -Path "bin/Release/net8.0/win-x86/publish/*" -DestinationPath "shell.win-x86.zip"
          Compress-Archive -Path "bin/Release/net8.0/win-arm64/publish/*" -DestinationPath "shell.win-arm64.zip"
        shell: pwsh

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            shell.win-x64.zip
            shell.win-x86.zip
            shell.win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
